title: HS Portfolio
email: hilarysoong@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: https://hilarycodelab.github.io # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  hilarycodelab
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  # projects:
  #   output: true
  #   permalink: /:collection/:path/
  # skills:
  #   output: true

# Build settings
# theme: minima
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon" #"default","air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
logo: "/assets/images/my_name_logo.png"
masthead_title: "Hilary Soong"
breadcrumbs: true  # disabled by default
author: Hilary Soong
layout: single
classes:
  - wide
  
sass:
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

defaults:
  #_projects
  # - scope:
  #     path: "_projects"
  #     type: projects
  #   values:
  #     layout: single
  #     author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
